version: '3.8'

services:

  db:
    image: mysql:latest
    restart: always
    ports:
      - "3307:3306"
    env_file:
      - .env.example
    volumes:
      - db_data:/var/lib/mysql
  
  api:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - db
    env_file:
      - .env.example
    restart: unless-stopped

volumes:
  db_data:
